export let tableAuthors = [
    {
        name: 'Esthera Jackson',
        email: 'esthera@simmmple.com',
        jobTitle: 'Manager',
        jobName:'Organization',
        isOnline: true,
        joined: '14/06/21',
    },
    {
        name: 'Alexa Liras',
        email: 'alexa@simmmple.com',
        jobTitle: 'Programmer',
        jobName:'Developer',
        isOnline: false,
        joined: '14/06/21',
    },
    {
        name: 'Laurent Michael',
        email: 'laurent@simmmple.com',
        jobTitle: 'Executive',
        jobName:'Projects',
        isOnline: true,
        joined: '14/06/21',
    },
    {
        name: 'Freduardo Hill',
        email: 'freduardo@simmmple.com',
        jobTitle: 'Manager',
        jobName:'Organization',
        isOnline: true,
        joined: '14/06/21',
    },
    {
        name: 'Daniel Thomas',
        email: 'daniel@simmmple.com',
        jobTitle: 'Programmer',
        jobName:'Developer',
        isOnline: false,
        joined: '14/06/21',
    },
    {
        name: 'Mark Wilson',
        email: 'mark@simmmple.com',
        jobTitle: 'Designer',
        jobName:'UI/UX Design',
        isOnline: false,
        joined: '14/06/21',
    },
    {
        name: 'Mark Wilson',
        email: 'mark@simmmple.com',
        jobTitle: 'Designer',
        jobName:'UI/UX Design',
        isOnline: false,
        joined: '14/06/21',
    },
    {
        name: 'Mark Wilson',
        email: 'mark@simmmple.com',
        jobTitle: 'Designer',
        jobName:'UI/UX Design',
        isOnline: false,
        joined: '14/06/21',
    }
]